### ISSUE TITLE
OpenWRT on Buffalo WSR-1166DHP3

### ISSUE THREAD

**Issue by LastStarDust** [musashino-build/openwrt_build-profiles#1]
Hello!
I would like to flash OpenWRT on a Buffalo WSR-1166DHP3 router.
This is the only place on the internet where this model is mentioned in reference to OpenWRT.
Could you please tell me if OpenWRT is compatible with this model and, in case, which firmware to flash?

I have found the following page on the OpenWRT site for the WSR-1166DHP model:
https://openwrt.org/toh/buffalo/wsr-1166dhp?s[]=wsr&s[]=1166dhp
But I am not sure if I can flash that firmware on my WSR-1166DHP3.
Thank you
Jojo

**Comment by musashino205** [comment]
Hello, jojo.

Unfortunately, there is no firmware that can be used for WSR-1166DHP3 if I say from the conclusion.

Unlike WSR-1166DHP / DHP2, this model has Realtek MIPS SoC. This SoC is not currently supported by OpenWrt, so we cannot build firmware for this model.

Comparison:

||WSR-1166DHP/DHP2|WSR-1166DHP3|
|:----:|:----:|:----:|
|SoC|MediaTek MT7621A|Realtek RTL8197F|
|OpenWrt|supported|not supported|
|target|ramips|(none)|

**Comment by musashino205** [comment]
I tried to add support for WSR-1166DHP3 before, but my knowledge of Linux Kernel and Embedded hardware was very lacking, so I gave up.

[rtkmips/rtl8197f/wsr-1166dhp3/diffconfig](/musashino-build/openwrt_build-profiles/blob/master/rtkmips/rtl8197f/wsr-1166dhp3/diffconfig) is diffconfig prepared at that time, but I have forgotten to delete it.

**Comment by LastStarDust** [comment]
Dear Inagaki-san,
thank you very much for the quick answer. Do you know other open source
firmwares other than openwrt that could be compatible with this router?
Best
Jojo

2018年6月3日(日) 1:43 INAGAKI Hiroshi <notifications@github.com>:

**Comment by musashino205** [comment]
As far as I know, there seems to be no open source firmwares supporting this model...

Realtek publishes an SDK for RTL819x SoC based on old OpenWrt, but since the hardware configuration of WSR-1166DHP3 is not defined, we need to create the definition for it.
[RTL819X download | SourceForge.net](https://sourceforge.net/projects/rtl819x/)

**Comment by LastStarDust** [comment]
I closed this issue because there has been no update for many years.
